### ISSUE TITLE
Multiple Delimiters Handling

### ISSUE THREAD

**Issue by aryes** [ffpojo/ffpojo#2]
Hi,

Thanks for publishing this library. it saves a lot of time and produces a very elegant code.

In the source I see that you delimit by regular expression.
This way there are empty strings when the file contains multiple delimiters one after the other.

Can you make it handle multiple delimiters?

Thanks,
Arye

P.S. I noticed you moved from sourceforge to here. ffpojo 0.1.jat can be downloaded from source forge, but I couldn't find it here. Is there a link here in github for the jar file?

**Comment by gibaholms** [comment]
Issue closed together with #10 .
