### ISSUE TITLE
Positional record with variable length last field

### ISSUE THREAD

**Issue by aryes** [ffpojo/ffpojo#4]
Hi,

Can you please add support for positional records that the last field length varies?

For example:

001   001   ABCD
002   002   A
003   003   SDFSDF

Thanks,
Arye

**Comment by gibaholms** [comment]
Hi, 
Unfortunately this would violate the concept of positional file... but you can accomplish this effect by declaring a positional field with a very big final position, making the last field "large" enough to accomodate your bigger value.
