### ISSUE TITLE
Allow @PositionalField on FIELD, not just METHOD

### ISSUE THREAD

**Issue by jacek99** [ffpojo/ffpojo#5]
@PositionalField annotations can only be placed on the getter. It does not allow itself to be placed on the field level (unlike JPA, JAXB, etc.)

if you are using Lombok in your application (which generates all the getters/setters automatically for you), this means you have to manually code each getter instead.

On a large file with multiple record types and dozes of fields per record this becomes quite painful to keep tying.

You can use apache coommons bean utils (PropertyUtils) to easily get the getter value from a field name.

Thanks!

**Comment by gibaholms** [comment]
Implemented for next release 1.1.
